steps:
  - name: maven:3.9.7-eclipse-temurin-21-alpine
    entrypoint: mvn
    args: ['test']

  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '--platform=linux/amd64',
        '-t',
        'europe-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/mkrolik-spring-social-api:latest',
        '.',
      ]
    env:
      - 'DOCKER_BUILDKIT=1'

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/mkrolik-spring-social-api:latest',
      ]

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: [
        'gcloud',
        'run',
        'deploy',
        'mkrolik-spring-social-api', # fixed name w/o "$SHORT_SHA"
        '--image=europe-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/mkrolik-spring-social-api:latest',
        '--region',
        'europe-west1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--max-instances',
        '3',
        '--port',
        '8080',
        '--set-secrets',
        'NEON_PASSWORD=NEON_PASSWORD:latest,NEON_USERNAME=NEON_USERNAME:latest,NEON_PORT=NEON_PORT:latest,NEON_HOSTNAME=NEON_HOSTNAME:latest,NEON_DATABASE=NEON_DATABASE:latest,USER_NAME=USER_NAME:latest,PASSWORD=PASSWORD:latest',
      ]

images:
  - europe-west1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/mkrolik-spring-social-api:latest

options:
  logging: CLOUD_LOGGING_ONLY
